export const CATEGORY_NAMES = {
  REFEITORIO: '01. ÁREA DE VIVÊNCIA: REFEITÓRIO',
  SANITARIAS: '02. ÁREA DE VIVÊNCIA: INSTALAÇÕES SANITÁRIAS',
  VESTIARIOS: '03. ÁREA DE VIVÊNCIA: VESTIÁRIOS',
  BEBEDOUROS: '04. ÁREA DE VIVÊNCIA: BEBEDOUROS',
  ELETRICAS: '05. INSTALAÇÕES ELÉTRICAS PROVISÓRIAS',
  DEMOLICAO: '06. DEMOLIÇÃO',
  ARMACAO: '07. ARMAÇÃO',
  ESCAVACAO: '08. ESCAVAÇÃO',
  CONCRETO: '09. ESTRUTURA DE CONCRETO ARMADO',
  METALICA: '10. ESTRUTURA METÁLICA',
  QUENTE: '11. TRABALHO A QUENTE',
  IMPERMEABILIZACAO: '12. IMPERMEABILIZAÇÃO',
  ESCADAS: '13. ESCADAS, RAMPAS E PASSARELAS',
  QUEDAS: '14. MEDIDAS DE PROTEÇÃO CONTRA QUEDAS DE ALTURA',
  EPIS: '15. EPIs',
  MAQUINAS: '16. MÁQUINAS, EQUIPAMENTOS E FERRAMENTAS',
  CONFINADO: '17. ESPAÇO CONFINADO',
  ALTURA: '18. TRABALHO EM ALTURA',
  ARMAZENAMENTO: '19. ARMAZENAMENTO DE MATERIAIS',
  LIMPEZA: '20. LIMPEZA E ORGANIZAÇÃO',
  ANDAIMES_SIMPLES: '21. ANDAIMES SIMPLES',
  ANDAIMES_FACHADEIROS: '22. ANDAIMES FACHADEIROS, MULTIDIRECIONAL',
  ANDAIMES_SUSPENSOS: '23. ANDAIMES SUSPENSOS, MOTORIZADOS E EM BALANÇO; CADEIRA SUSPENSA',
  GRUA: '24. GRUA, MINI GRUA E EQUIPAMENTOS DE GUINDASTE',
  ELEVADOR: '25. ELEVADOR PROVISÓRIO',
  ALMOXARIFADO: '26. ALMOXARIFADO E RECEBIMENTO DE MATERIAIS',
  PORTARIA: '27. PORTARIA E ACESSO',
  INCENDIO: '28. COMBATE A INCÊNDIO E SITUAÇÕES DE EMERGÊNCIA',
  SINALIZACAO: '29. SINALIZAÇÃO DE SEGURANÇA',
  DOCUMENTACAO_BASICA: '30. DOCUMENTAÇÃO BÁSICA',
  TREINAMENTOS: '31. TREINAMENTOS',
  DOCUMENTACAO_LEGAL: '32. DOCUMENTAÇÃO LEGAL',
  PROGRAMAS: '33. PROGRAMAS E PROJETOS',
  ACIDENTES: '34. ACIDENTES E INCIDENTES'
};

export const SAFETY_QUESTIONS = [
  // 01. ÁREA DE VIVÊNCIA: REFEITÓRIO
  { id: '01-01', category: 'REFEITORIO', question: 'Local para refeição sem comunicação direta com instalações sanitárias, com cobertura, paredes para isolamento e piso lavável', weight: 3 },
  { id: '01-02', category: 'REFEITORIO', question: 'Higiene/limpeza: lixeira com tampa 75 L / lavatório (proximidades ou interior)', weight: 2 },
  { id: '01-03', category: 'REFEITORIO', question: 'Mesas com tampos laváveis e bancos que atendem 60% do efetivo padrão', weight: 2 },
  { id: '01-04', category: 'REFEITORIO', question: 'Ventilação e iluminação natural ou artificial, vãos telados', weight: 0.5 },
  { id: '01-05', category: 'REFEITORIO', question: 'Aquecedor tipo estufa para 70% do efetivo e bebedouro industrial K200', weight: 1 },
  { id: '01-06', category: 'REFEITORIO', question: 'TV com Wi-Fi', weight: 0.5 },
  { id: '01-07', category: 'REFEITORIO', question: 'Outros', weight: 1 },

  // 02. ÁREA DE VIVÊNCIA: INSTALAÇÕES SANITÁRIAS
  { id: '02-01', category: 'SANITARIAS', question: 'Outros', weight: 2 },
  { id: '02-02', category: 'SANITARIAS', question: 'Vaso sanitário 1/20 com descarga automática e assentos com tampa em boa condição', weight: 5 },
  { id: '02-03', category: 'SANITARIAS', question: 'Área mínima de 1 m² no local para vaso sanitário, divisória de no mínimo 1,80 m', weight: 4 },
  { id: '02-04', category: 'SANITARIAS', question: 'Porta com trinco', weight: 3 },
  { id: '02-05', category: 'SANITARIAS', question: 'Suporte para papel higiênico padrão', weight: 2 },
  { id: '02-06', category: 'SANITARIAS', question: 'Lixeira com tampa 12 L; lixeira 75 L para papéis do lavatório', weight: 4 },
  { id: '02-07', category: 'SANITARIAS', question: 'Mictório e lavatório 1/20', weight: 4 },
  { id: '02-08', category: 'SANITARIAS', question: 'Chuveiro 1/10 com água quente', weight: 3 },
  { id: '02-09', category: 'SANITARIAS', question: 'Estrado plástico para piso; saboneteira e porta-toalha para cada chuveiro', weight: 5 },
  { id: '02-10', category: 'SANITARIAS', question: 'Instalações elétricas protegidas com DR, aterradas e com laudo/ART', weight: 4 },
  { id: '02-11', category: 'SANITARIAS', question: 'Higiene/limpeza: piso e paredes revestidos de material impermeável e lavável', weight: 4 },
  { id: '02-12', category: 'SANITARIAS', question: 'O deslocamento do trabalhador do posto ao sanitário não pode ser superior a 150 m', weight: 4 },

  // 03. ÁREA DE VIVÊNCIA: VESTIÁRIOS
  { id: '03-01', category: 'VESTIARIOS', question: 'Outros', weight: 2 },
  { id: '03-02', category: 'VESTIARIOS', question: 'Local coberto para vestiário com ventilação considerando no mínimo 1/10', weight: 4 },
  { id: '03-03', category: 'VESTIARIOS', question: 'Armário com fechadura ou lugar para cadeado, com identificação', weight: 4 },
  { id: '03-04', category: 'VESTIARIOS', question: 'Bancos de largura mínima de 0,30 m; local para armazenar botinas', weight: 3 },
  { id: '03-05', category: 'VESTIARIOS', question: 'Condição das paredes de alvenaria, madeira ou equivalente nas cores padrão', weight: 3 },
  { id: '03-06', category: 'VESTIARIOS', question: 'Condição do piso de concreto, cimentado, madeira ou equivalente', weight: 3 },
  { id: '03-07', category: 'VESTIARIOS', question: 'Higiene/limpeza: lixeira com tampa 75 L', weight: 3 },
  { id: '03-08', category: 'VESTIARIOS', question: 'Iluminação e ventilação natural ou artificial', weight: 3 },
  { id: '03-09', category: 'VESTIARIOS', question: 'Varal ou projeto de toalha', weight: 2 },

  // 04. ÁREA DE VIVÊNCIA: BEBEDOUROS
  { id: '04-01', category: 'BEBEDOUROS', question: 'Outros', weight: 2 },
  { id: '04-02', category: 'BEBEDOUROS', question: 'Fornecimento de bebedouro com água filtrada e fresca', weight: 4 },
  { id: '04-03', category: 'BEBEDOUROS', question: 'Filtro com troca em dia', weight: 4 },
  { id: '04-04', category: 'BEBEDOUROS', question: 'Espaçamento considerando 100 cm na horizontal e 15 cm na vertical', weight: 3 },
  { id: '04-05', category: 'BEBEDOUROS', question: 'Local coberto com painel padrão', weight: 3 },
  { id: '04-06', category: 'BEBEDOUROS', question: 'Integridade dos plugs; aterramento com laudo/ART; Limpeza', weight: 4 },

  // 05. INSTALAÇÕES ELÉTRICAS PROVISÓRIAS
  { id: '05-01', category: 'ELETRICAS', question: 'Outros', weight: 2 },
  { id: '05-02', category: 'ELETRICAS', question: 'Serviços executados por colaboradores autorizados e identificados, sinalização de risco de choque', weight: 5 },
  { id: '05-03', category: 'ELETRICAS', question: 'Circuitos e equipamentos sem partes vivas expostas', weight: 5 },
  { id: '05-04', category: 'ELETRICAS', question: 'Condutores sem obstruir circulação de pessoas e materiais', weight: 4 },
  { id: '05-05', category: 'ELETRICAS', question: 'Condutores protegidos contra impactos mecânicos, umidade e agentes danificadores', weight: 5 },
  { id: '05-06', category: 'ELETRICAS', question: 'Compatibilidade de condutores com capacidade dos circuitos e identificação dos circuitos', weight: 4 },
  { id: '05-07', category: 'ELETRICAS', question: 'Isolação conforme normas vigentes', weight: 5 },
  { id: '05-08', category: 'ELETRICAS', question: 'Quadro de distribuição trancado e aterrado; partes vivas inacessíveis e protegidas; acesso desobstruído', weight: 5 },
  { id: '05-09', category: 'ELETRICAS', question: 'Uso de plugues e tomadas específicos para máquinas, equipamentos, ferramentas e extensões', weight: 4 },
  { id: '05-10', category: 'ELETRICAS', question: 'Utilização de DR nos robôs e quadros de distribuição', weight: 5 },
  { id: '05-11', category: 'ELETRICAS', question: 'Aterramentos de equipamentos, área de vivência e canteiro', weight: 5 },
  { id: '05-12', category: 'ELETRICAS', question: 'Iluminação dos ambientes', weight: 3 },
  { id: '05-13', category: 'ELETRICAS', question: 'Extensões e cabos aéreos', weight: 4 },
  { id: '05-14', category: 'ELETRICAS', question: 'Projeto de instalações provisórias contendo diagrama unifilar, declaração de carga instalada, prontuário e SPDA (ou dispensa) conforme NR-10', weight: 5 },

  // 06. DEMOLIÇÃO
  { id: '06-01', category: 'DEMOLICAO', question: 'Outros', weight: 2 },
  { id: '06-02', category: 'DEMOLICAO', question: 'Plano de demolição elaborado e implementado por profissional habilitado (conforme NR-18)', weight: 5 },
  { id: '06-03', category: 'DEMOLICAO', question: 'Laudo de vizinhança', weight: 4 },
  { id: '06-04', category: 'DEMOLICAO', question: 'Remoção de elementos frágeis antes da demolição', weight: 4 },
  { id: '06-05', category: 'DEMOLICAO', question: 'Escadas e rotas de fuga desimpedidas', weight: 5 },
  { id: '06-06', category: 'DEMOLICAO', question: 'Proibição de lançamento em queda livre de qualquer material', weight: 5 },
  { id: '06-07', category: 'DEMOLICAO', question: 'Utilização de duto para retirada de entulhos com inclinação máxima de 45°', weight: 4 },
  { id: '06-08', category: 'DEMOLICAO', question: 'Lona no final do duto para evitar dispersão de poeira', weight: 3 },
  { id: '06-09', category: 'DEMOLICAO', question: 'Não abandonar elementos que possam desabar', weight: 5 },
  { id: '06-10', category: 'DEMOLICAO', question: 'Umedecer materiais antes da demolição para reduzir poeira', weight: 3 },
  { id: '06-11', category: 'DEMOLICAO', question: 'Gestão de resíduos', weight: 4 },
  { id: '06-12', category: 'DEMOLICAO', question: 'Projetos e ART dos sistemas e plano de demolição', weight: 5 },

  // 07. ARMAÇÃO
  { id: '07-01', category: 'ARMACAO', question: 'Outros', weight: 2 },
  { id: '07-02', category: 'ARMACAO', question: 'Serra policorte em conformidade com NR-12 e NR-18', weight: 5 },
  { id: '07-03', category: 'ARMACAO', question: 'Área de montagem de armação coberta com piso resistente, nivelado e antiderrapante', weight: 4 },
  { id: '07-04', category: 'ARMACAO', question: 'Proteção nas pontas dos vergalhões; área isolada, sinalizada e limpa', weight: 5 },

  // 08. ESCAVAÇÃO
  { id: '08-01', category: 'ESCAVACAO', question: 'Outros', weight: 2 },
  { id: '08-02', category: 'ESCAVACAO', question: 'Serviço de escavação, fundação e desmonte de rochas executado e supervisionado conforme projeto por profissional habilitado', weight: 5 },
  { id: '08-03', category: 'ESCAVACAO', question: 'Sinalização de advertência, barreira, sinalização noturna se necessário', weight: 4 },
  { id: '08-04', category: 'ESCAVACAO', question: 'Barreiras de isolamento em todo o perímetro', weight: 5 },
  { id: '08-05', category: 'ESCAVACAO', question: 'Profundidade superior a 1,25 m somente iniciada com autorização de profissional habilitado', weight: 5 },
  { id: '08-06', category: 'ESCAVACAO', question: 'Talude de escavação protegido contra erosão interna e superficial', weight: 4 },
  { id: '08-07', category: 'ESCAVACAO', question: 'Projeto de escavações considerando solo, cargas e medidas de prevenção', weight: 5 },
  { id: '08-08', category: 'ESCAVACAO', question: 'Desníveis protegidos: até 1 m com tela de sinalização, acima de 1 m guarda-corpo rígido', weight: 5 },
  { id: '08-09', category: 'ESCAVACAO', question: 'Faixa de proteção mínima de 1 m nas bordas livre de cargas e proteção contra águas superficiais', weight: 4 },
  { id: '08-10', category: 'ESCAVACAO', question: 'Passarelas para trânsito sobre escavações', weight: 4 },
  { id: '08-11', category: 'ESCAVACAO', question: 'Escoramentos inspecionados diariamente', weight: 5 },
  { id: '08-12', category: 'ESCAVACAO', question: 'Desvio de tráfego próximo ou redução de velocidade de veículos', weight: 4 },
  { id: '08-13', category: 'ESCAVACAO', question: 'Serviços com tubulão a céu aberto conforme procedimento específico', weight: 4 },
  { id: '08-14', category: 'ESCAVACAO', question: 'Rampas para veículos com largura dupla do maior veículo e guardas-corpo quando necessário', weight: 4 },
  { id: '08-15', category: 'ESCAVACAO', question: 'Escada coletiva de madeira até 1 subsolo e metálica acima, acesso seguro dos trabalhadores', weight: 4 },
  { id: '08-16', category: 'ESCAVACAO', question: 'Lava rodas e conservação das vias públicas', weight: 3 },

  // 09. ESTRUTURA DE CONCRETO ARMADO
  { id: '09-01', category: 'CONCRETO', question: 'Outros', weight: 2 },
  { id: '09-02', category: 'CONCRETO', question: 'Escoramento e reescoramento montado conforme projeto', weight: 5 },
  { id: '09-03', category: 'CONCRETO', question: 'Plataforma para montagem de pilares conforme projeto (pilares acima de 80 cm)', weight: 4 },
  { id: '09-04', category: 'CONCRETO', question: 'Proteção nas pontas dos vergalhões', weight: 5 },
  { id: '09-05', category: 'CONCRETO', question: 'Vãos de passagem para materiais protegidos', weight: 4 },
  { id: '09-06', category: 'CONCRETO', question: 'Proteção de concretagem e de montagem de viga de borda', weight: 4 },
  { id: '09-07', category: 'CONCRETO', question: 'Vibradores de concreto devidamente instalados', weight: 4 },
  { id: '09-08', category: 'CONCRETO', question: 'Isolamento das áreas de desforma', weight: 4 },
  { id: '09-09', category: 'CONCRETO', question: 'Acesso seguro dos trabalhadores para laje em assoalhamento', weight: 5 },
  { id: '09-10', category: 'CONCRETO', question: 'Organização e caminho seguro', weight: 4 },
  { id: '09-11', category: 'CONCRETO', question: 'Óculos de segurança', weight: 4 },

  // 10. ESTRUTURA METÁLICA
  { id: '10-01', category: 'METALICA', question: 'Outros', weight: 2 },
  { id: '10-02', category: 'METALICA', question: 'Supervisão por profissional habilitado', weight: 5 },
  { id: '10-03', category: 'METALICA', question: 'SPIQ e meios de acesso previstos no PGR da obra', weight: 5 },
  { id: '10-04', category: 'METALICA', question: 'Área de armazenamento organizada', weight: 3 },

  // 11. TRABALHO A QUENTE
  { id: '11-01', category: 'QUENTE', question: 'Outros', weight: 2 },
  { id: '11-02', category: 'QUENTE', question: 'Realização por colaboradores capacitados, com observador em combate a incêndio', weight: 5 },
  { id: '11-03', category: 'QUENTE', question: 'Dispositivo para manusear eletrodos com isolamento adequado', weight: 4 },
  { id: '11-04', category: 'QUENTE', question: 'Anteparo eficaz de material incombustível (biombo)', weight: 4 },
  { id: '11-05', category: 'QUENTE', question: 'Mecanismo contra retrocesso de chamas no cilindro e mangueiras', weight: 5 },
  { id: '11-06', category: 'QUENTE', question: 'Uso de acendedores apropriados', weight: 4 },
  { id: '11-07', category: 'QUENTE', question: 'Mangueiras sem emendas e em condições adequadas', weight: 4 },
  { id: '11-08', category: 'QUENTE', question: 'Inexistência de materiais inflamáveis/explosivos próximos aos cilindros', weight: 5 },
  { id: '11-09', category: 'QUENTE', question: 'Equipamentos de soldagem aterrados', weight: 5 },
  { id: '11-10', category: 'QUENTE', question: 'Ventilação local exaustora natural ou forçada', weight: 4 },
  { id: '11-11', category: 'QUENTE', question: 'Manômetros, reguladores de oxigênio e acetileno em condições adequadas', weight: 4 },
  { id: '11-12', category: 'QUENTE', question: 'Acondicionamento adequado dos cilindros (ventilado e acesso restrito)', weight: 4 },
  { id: '11-13', category: 'QUENTE', question: 'Transporte em carrinhos, na posição vertical, com capacete rosqueado', weight: 4 },
  { id: '11-14', category: 'QUENTE', question: 'Local de serviço sem substâncias combustíveis no entorno; válvulas fechadas quando inoperantes', weight: 4 },
  { id: '11-15', category: 'QUENTE', question: 'Documentações e acessórios conforme', weight: 3 },
  { id: '11-16', category: 'QUENTE', question: 'Extintor PQS ou CO2', weight: 5 },
  { id: '11-17', category: 'QUENTE', question: 'Proibição de cilindros P13', weight: 4 },

  // 12. IMPERMEABILIZAÇÃO
  { id: '12-01', category: 'IMPERMEABILIZACAO', question: 'Outros', weight: 2 },
  { id: '12-02', category: 'IMPERMEABILIZACAO', question: 'Baia para armazenamento de inflamáveis', weight: 4 },
  { id: '12-03', category: 'IMPERMEABILIZACAO', question: 'Cilindro de 45 kg com carrinho, manômetro funcionando e sem vazamento', weight: 5 },
  { id: '12-04', category: 'IMPERMEABILIZACAO', question: 'Mangueira > 5 m sem emendas, válvulas antichamas', weight: 4 },
  { id: '12-05', category: 'IMPERMEABILIZACAO', question: 'Aquecedor com tampa, identificação do fabricante, termostato', weight: 4 },
  { id: '12-06', category: 'IMPERMEABILIZACAO', question: 'Recipiente com tampa para transporte de asfalto', weight: 3 },
  { id: '12-07', category: 'IMPERMEABILIZACAO', question: 'Documentação do equipamento, manual e treinamento', weight: 4 },
  { id: '12-08', category: 'IMPERMEABILIZACAO', question: 'EPIs obrigatórios: respirador, protetor facial, perneira, luva, avental', weight: 5 },
  { id: '12-09', category: 'IMPERMEABILIZACAO', question: 'Treinamento para impermeabilizadores', weight: 4 },

  // 13. ESCADAS, RAMPAS E PASSARELAS
  { id: '13-01', category: 'ESCADAS', question: 'Outros', weight: 2 },
  { id: '13-02', category: 'ESCADAS', question: 'Madeira sem nós ou rachaduras, seca e sem pintura', weight: 4 },
  { id: '13-03', category: 'ESCADAS', question: 'Escada coletiva largura ≥ 0,80 m, guarda-corpo 1,20 m, travessões e rodapé', weight: 5 },
  { id: '13-04', category: 'ESCADAS', question: 'Escadas/rampas para desníveis > 40 cm', weight: 4 },
  { id: '13-05', category: 'ESCADAS', question: 'Escada de mão até 3 m, espaçamento 0,25–0,30 m e ultrapassar 1 m do piso superior', weight: 4 },
  { id: '13-06', category: 'ESCADAS', question: 'Escadas de mão apoiadas em pisos resistentes', weight: 4 },
  { id: '13-07', category: 'ESCADAS', question: 'Escadas de mão não devem estar próximos a redes e equipamentos elétricos desprotegidos', weight: 5 },
  { id: '13-08', category: 'ESCADAS', question: 'Proibido colocar escadas de mão ou portátil próximos a portas, aberturas e vãos', weight: 5 },
  { id: '13-09', category: 'ESCADAS', question: 'Escada de mão ou portátil com fixação nos pisos ou dispositivo que impeça o seu escorregamento', weight: 4 },
  { id: '13-10', category: 'ESCADAS', question: 'As escadas portáteis devem ser usadas por uma pessoa de cada vez, exceto quando especificado pelo fabricante o uso simultâneo', weight: 4 },
  { id: '13-11', category: 'ESCADAS', question: 'Escadas portáteis nas proximidades de portas ou áreas de circulação, a área no entorno dos serviços deve ser isolada e sinalizada', weight: 4 },
  { id: '13-12', category: 'ESCADAS', question: 'Escada extensível com limitador de curso, com sobreposição mínima de 1m', weight: 4 },
  { id: '13-13', category: 'ESCADAS', question: 'Rampas provisórias não devem ultrapassar 30°', weight: 4 },
  { id: '13-14', category: 'ESCADAS', question: 'Rampas entre 18° e 30° devem ter fixadas peças transversais', weight: 4 },
  { id: '13-15', category: 'ESCADAS', question: 'Escada definitiva com alçapão instalado', weight: 3 },

  // 14. MEDIDAS DE PROTEÇÃO CONTRA QUEDAS DE ALTURA
  { id: '14-01', category: 'QUEDAS', question: 'Outros', weight: 2 },
  { id: '14-02', category: 'QUEDAS', question: 'SLQA: instalação, ascensão, manutenção e eficácia do sistema', weight: 5 },
  { id: '14-03', category: 'QUEDAS', question: 'Rede piso-piso: instalação e manutenção', weight: 5 },
  { id: '14-04', category: 'QUEDAS', question: 'Proteção de periferia de lajes pós-concretagem (metálica)', weight: 5 },
  { id: '14-05', category: 'QUEDAS', question: 'Plataformas/bandejas (primária, secundária, terciária)', weight: 5 },
  { id: '14-06', category: 'QUEDAS', question: 'Bandeja intermediária conforme plano de segurança, no máximo 3 lajes abaixo do bolsão', weight: 4 },
  { id: '14-07', category: 'QUEDAS', question: 'Tela de fachadeira', weight: 4 },
  { id: '14-08', category: 'QUEDAS', question: 'Poço do elevador: fechamento total vertical, fechamento horizontal com tela eletrosoldada do vão etapa estrutura com assoalho nas 2 últimas lajes e abaixo a cada 3 andares', weight: 5 },
  { id: '14-09', category: 'QUEDAS', question: 'Poço do elevador: fechamento total do vão etapa de montagem elevador (porta bipartida metálica)', weight: 5 },
  { id: '14-10', category: 'QUEDAS', question: 'Proteção de shafts com espuma', weight: 4 },
  { id: '14-11', category: 'QUEDAS', question: 'Proteção de shaft, aberturas no piso e vãos de pressurização com tela eletrosoldada e assoalho de madeira', weight: 4 },
  { id: '14-12', category: 'QUEDAS', question: 'Proteção de varandas', weight: 4 },
  { id: '14-13', category: 'QUEDAS', question: 'Proteção de calçada', weight: 4 },
  { id: '14-14', category: 'QUEDAS', question: 'Proteção de vizinhos', weight: 5 },
  { id: '14-15', category: 'QUEDAS', question: 'Galeria de proteção interna para visitantes e colaboradores', weight: 5 },
  { id: '14-16', category: 'QUEDAS', question: 'Galeria de proteção externa de pedestres', weight: 5 },
  { id: '14-17', category: 'QUEDAS', question: 'Linha de vida para a estrutura (haste de segurança) nível assoalho, nível escoramento e nível desforma', weight: 4 },
  { id: '14-18', category: 'QUEDAS', question: 'Linhas de vida em terraços', weight: 4 },

  // 15. EPIs
  { id: '15-01', category: 'EPIS', question: 'Outros', weight: 2 },
  { id: '15-02', category: 'EPIS', question: 'Capacete com jugular', weight: 5 },
  { id: '15-03', category: 'EPIS', question: 'Óculos de proteção', weight: 4 },
  { id: '15-04', category: 'EPIS', question: 'Calçado de segurança; bota de borracha', weight: 5 },
  { id: '15-05', category: 'EPIS', question: 'Luva de proteção; avental; perneira; mangote', weight: 4 },
  { id: '15-06', category: 'EPIS', question: 'Protetor facial; respirador semifacial; protetor auditivo', weight: 4 },
  { id: '15-07', category: 'EPIS', question: 'Conjunto Trevira; colete refletivo', weight: 3 },
  { id: '15-08', category: 'EPIS', question: 'Cinto de segurança com talabarte ou trava-quedas', weight: 5 },
  { id: '15-09', category: 'EPIS', question: 'Uniforme', weight: 3 },
  { id: '15-10', category: 'EPIS', question: 'Protetor solar', weight: 3 },

  // 16. MÁQUINAS, EQUIPAMENTOS E FERRAMENTAS
  { id: '16-01', category: 'MAQUINAS', question: 'Outros', weight: 2 },
  { id: '16-02', category: 'MAQUINAS', question: 'Serra de bancada conforme NR-12 e NR-18', weight: 5 },
  { id: '16-03', category: 'MAQUINAS', question: 'Trabalhador qualificado e identificado com crachá', weight: 4 },
  { id: '16-04', category: 'MAQUINAS', question: 'Partes móveis protegidas contra projeção de partículas', weight: 5 },
  { id: '16-05', category: 'MAQUINAS', question: 'Proteção contra intempéries', weight: 3 },
  { id: '16-06', category: 'MAQUINAS', question: 'Abastecimento realizado por funcionário qualificado', weight: 4 },
  { id: '16-07', category: 'MAQUINAS', question: 'Botão de emergência ou dispositivo de bloqueio', weight: 5 },
  { id: '16-08', category: 'MAQUINAS', question: 'Manutenção preventiva; manual de instruções', weight: 4 },
  { id: '16-09', category: 'MAQUINAS', question: 'Alarme sonoro para ré; check-list; proteção para ferramentas pontiagudas', weight: 4 },
  { id: '16-10', category: 'MAQUINAS', question: 'Ferramentas pneumáticas portáteis com dispositivo de partida', weight: 4 },
  { id: '16-11', category: 'MAQUINAS', question: 'Ferramentas elétricas manuais com duplo isolamento', weight: 5 },
  { id: '16-12', category: 'MAQUINAS', question: 'Misturadores e betoneiras', weight: 4 },
  { id: '16-13', category: 'MAQUINAS', question: 'Os vibradores para o concreto devem ter dupla isolação e cabos protegidos contra choques mecânicos e cortes pela ferragem', weight: 5 },

  // 17. ESPAÇO CONFINADO
  { id: '17-01', category: 'CONFINADO', question: 'Outros', weight: 2 },
  { id: '17-02', category: 'CONFINADO', question: 'Treinamento e orientação aos colaboradores sobre os riscos que estão submetidos NR 33', weight: 5 },
  { id: '17-03', category: 'CONFINADO', question: 'Inspeção prévia do local e elaboração de OS com os procedimentos a serem adotados NR 33', weight: 5 },
  { id: '17-04', category: 'CONFINADO', question: 'Sistema de exaustão. Não utilizar oxigênio para ventilação de local confinado NR 33', weight: 5 },
  { id: '17-05', category: 'CONFINADO', question: 'Sinalização durante a realização de trabalhos no interior de espaços confinados NR 33', weight: 4 },
  { id: '17-06', category: 'CONFINADO', question: 'Acondicionamento adequado de substâncias tóxicas ou inflamáveis NR 33', weight: 5 },

  // 18. TRABALHO EM ALTURA
  { id: '18-01', category: 'ALTURA', question: 'Outros', weight: 2 },
  { id: '18-02', category: 'ALTURA', question: 'Sistema de autorização de colaboradores a atividades em altura NR 35', weight: 5 },
  { id: '18-03', category: 'ALTURA', question: 'Trabalho planejado e organizado com inspeção prévia e condição adequada do local conforme NR 35', weight: 5 },

  // 19. ARMAZENAMENTO DE MATERIAIS
  { id: '19-01', category: 'ARMAZENAMENTO', question: 'Outros', weight: 2 },
  { id: '19-02', category: 'ARMAZENAMENTO', question: 'Armazenamento deve ter forma e altura que garanta sua estabilidade e facilitem o manuseio', weight: 4 },
  { id: '19-03', category: 'ARMAZENAMENTO', question: 'Os materiais devem ser armazenados e estocados de modo a não ocasionar acidentes, prejudicar o trânsito de pessoas, a circulação de materiais, o acesso aos equipamentos de combate a incêndio e não obstruir portas ou saídas de emergência', weight: 5 },
  { id: '19-04', category: 'ARMAZENAMENTO', question: 'Os materiais não podem ser empilhados diretamente sobre piso instável, úmido ou desnivelado', weight: 4 },
  { id: '19-05', category: 'ARMAZENAMENTO', question: 'Os materiais tóxicos e inflamáveis devem ser armazenados em locais isolados apropriados, sinalizados e de acesso permitido somente a pessoas autorizadas', weight: 5 },
  { id: '19-06', category: 'ARMAZENAMENTO', question: 'Os funcionários autorizados a mexer com materiais tóxicos e inflamáveis devem ter conhecimento prévio do procedimento a ser adotado no caso de eventual acidente - treinamento na FISPQ', weight: 4 },
  { id: '19-07', category: 'ARMAZENAMENTO', question: 'Materiais a serem reutilizados (madeirites, formas, tapumes) devem ter seus pregos retirados ou rebatidos antes de serem armazenados', weight: 3 },

  // 20. LIMPEZA E ORGANIZAÇÃO
  { id: '20-01', category: 'LIMPEZA', question: 'Outros', weight: 2 },
  { id: '20-02', category: 'LIMPEZA', question: 'Pavimentos/áreas comuns', weight: 4 },
  { id: '20-03', category: 'LIMPEZA', question: 'Últimas lajes', weight: 4 },
  { id: '20-04', category: 'LIMPEZA', question: 'Remoção de entulho', weight: 4 },
  { id: '20-05', category: 'LIMPEZA', question: 'Controle de acúmulo de água', weight: 3 },

  // 21. ANDAIMES SIMPLES
  { id: '21-01', category: 'ANDAIMES_SIMPLES', question: 'Outros', weight: 2 },
  { id: '21-02', category: 'ANDAIMES_SIMPLES', question: 'Liberação do técnico de segurança com placa, trabalho sobre o equipamento conforme e check list preenchido', weight: 5 },
  { id: '21-03', category: 'ANDAIMES_SIMPLES', question: 'Estrutura montada corretamente, conforme manual em português com guarda corpo, sapata ou rodízio e tela, apoiado quando exceder 4 (quatro) vezes a menor dimensão da base de apoio', weight: 5 },
  { id: '21-04', category: 'ANDAIMES_SIMPLES', question: 'Treinamento para montador', weight: 4 },
  { id: '21-05', category: 'ANDAIMES_SIMPLES', question: 'ART de fabricação', weight: 4 },
  { id: '21-06', category: 'ANDAIMES_SIMPLES', question: 'Andaime sobre cavalete, largura mínima de 0,90m e altura máxima de 1,20m', weight: 4 },

  // 22. ANDAIMES FACHADEIROS, MULTIDIRECIONAL
  { id: '22-01', category: 'ANDAIMES_FACHADEIROS', question: 'Outros', weight: 2 },
  { id: '22-02', category: 'ANDAIMES_FACHADEIROS', question: 'Liberação do técnico de segurança com placa, trabalho sobre o equipamento conforme e check list diário', weight: 5 },
  { id: '22-03', category: 'ANDAIMES_FACHADEIROS', question: 'Treinamento dos montadores e operadores', weight: 4 },
  { id: '22-04', category: 'ANDAIMES_FACHADEIROS', question: 'Montagem conforme projeto e manual, ART do equipamento, e montagem', weight: 5 },

  // 23. ANDAIMES SUSPENSOS, MOTORIZADOS E EM BALANÇO; CADEIRA SUSPENSA
  { id: '23-01', category: 'ANDAIMES_SUSPENSOS', question: 'Outros', weight: 2 },
  { id: '23-02', category: 'ANDAIMES_SUSPENSOS', question: 'Termo de entrega técnica, ART do equipamento e demais documentos pertinentes', weight: 5 },
  { id: '23-03', category: 'ANDAIMES_SUSPENSOS', question: 'Trabalho com ferramentas amarradas', weight: 4 },
  { id: '23-04', category: 'ANDAIMES_SUSPENSOS', question: 'Identificação dos autorizados', weight: 4 },
  { id: '23-05', category: 'ANDAIMES_SUSPENSOS', question: 'Área isolada abaixo da atividade', weight: 5 },
  { id: '23-06', category: 'ANDAIMES_SUSPENSOS', question: 'Check list diário preenchido', weight: 4 },
  { id: '23-07', category: 'ANDAIMES_SUSPENSOS', question: 'Montagem conforme projeto, ART do equipamento, montagem e uso', weight: 5 },

  // 24. GRUA, MINI GRUA E EQUIPAMENTOS DE GUINDASTE
  { id: '24-01', category: 'GRUA', question: 'Outros', weight: 2 },
  { id: '24-02', category: 'GRUA', question: 'Termo de entrega técnica, laudo mecânico, laudo elétrico com ART', weight: 5 },
  { id: '24-03', category: 'GRUA', question: 'Check-list diário realizado pelo operador e sinaleiro', weight: 5 },
  { id: '24-04', category: 'GRUA', question: 'Identificação dos operadores autorizados e sinaleiros', weight: 4 },
  { id: '24-05', category: 'GRUA', question: 'Içamento e amarração correta com identificação e isolamento da área', weight: 5 },
  { id: '24-06', category: 'GRUA', question: 'Plano de carga, conforme 18.10.1.17', weight: 5 },

  // 25. ELEVADOR PROVISÓRIO
  { id: '25-01', category: 'ELEVADOR', question: 'Outros', weight: 2 },
  { id: '25-02', category: 'ELEVADOR', question: 'Botão de chamada, botão de emergência, botão de acionamento com dispositivo de bloqueio e painel de comando do elevador', weight: 5 },
  { id: '25-03', category: 'ELEVADOR', question: 'Sistema de intertravamento das cancelas com ruptura positiva', weight: 5 },
  { id: '25-04', category: 'ELEVADOR', question: 'Isolamento do operador com sensor e altura de 1,80 metros', weight: 4 },
  { id: '25-05', category: 'ELEVADOR', question: 'Cancelas, fechamento na lateral das cancelas, rampa de acesso e proteção da base', weight: 4 },
  { id: '25-06', category: 'ELEVADOR', question: 'Rampa com acesso seguro entre o elevador e o prédio', weight: 4 },
  { id: '25-07', category: 'ELEVADOR', question: 'Régua de cremalheira invertida no último módulo', weight: 5 },
  { id: '25-08', category: 'ELEVADOR', question: 'Elevador de passageiros instalado a partir de 15 metros no plano vertical', weight: 5 },
  { id: '25-09', category: 'ELEVADOR', question: 'Interruptor de movimento das portas da cabine e sensor de abertura das cancelas', weight: 5 },

  // 26. ALMOXARIFADO E RECEBIMENTO DE MATERIAIS
  { id: '26-01', category: 'ALMOXARIFADO', question: 'Outros', weight: 2 },
  { id: '26-02', category: 'ALMOXARIFADO', question: 'FISPQ dos produtos químicos', weight: 4 },
  { id: '26-03', category: 'ALMOXARIFADO', question: 'Limpeza, organização e armazenamento adequado', weight: 4 },
  { id: '26-04', category: 'ALMOXARIFADO', question: 'Sinalização das áreas de recebimento, carga e descarga de materiais', weight: 3 },

  // 27. PORTARIA E ACESSO
  { id: '27-01', category: 'PORTARIA', question: 'Outros', weight: 2 },
  { id: '27-02', category: 'PORTARIA', question: 'Controle de acesso', weight: 4 },
  { id: '27-03', category: 'PORTARIA', question: 'Capacete de visitantes com jugular', weight: 4 },
  { id: '27-04', category: 'PORTARIA', question: 'Sinalização e comunicação visual', weight: 4 },
  { id: '27-05', category: 'PORTARIA', question: 'Caminho seguro', weight: 3 },
  { id: '27-06', category: 'PORTARIA', question: 'Calço para veículos enquanto estacionados', weight: 3 },

  // 28. COMBATE A INCÊNDIO E SITUAÇÕES DE EMERGÊNCIA
  { id: '28-01', category: 'INCENDIO', question: 'Outros', weight: 2 },
  { id: '28-02', category: 'INCENDIO', question: 'Distribuição de extintores no canteiro, área de vivência e quadros elétricos, máquinas e equipamentos', weight: 5 },
  { id: '28-03', category: 'INCENDIO', question: 'Rotas de fuga e ponto de encontro', weight: 4 },
  { id: '28-04', category: 'INCENDIO', question: 'Alarme sonoro para evacuação', weight: 4 },
  { id: '28-05', category: 'INCENDIO', question: 'Check-list de extintores', weight: 4 },
  { id: '28-06', category: 'INCENDIO', question: 'Baia de inflamáveis e resíduos perigosos', weight: 4 },
  { id: '28-07', category: 'INCENDIO', question: 'Plano de emergência com simulado e equipe de brigada treinada', weight: 5 },
  { id: '28-08', category: 'INCENDIO', question: 'Kit CIPA e primeiros socorros conforme PCMSO', weight: 4 },

  // 29. SINALIZAÇÃO DE SEGURANÇA
  { id: '29-01', category: 'SINALIZACAO', question: 'Outros', weight: 2 },
  { id: '29-02', category: 'SINALIZACAO', question: 'Comunicação visual do canteiro, indicando acesso à obra, identificação dos andares, área de vivência e uso dos EPIs padrão', weight: 4 },
  { id: '29-03', category: 'SINALIZACAO', question: 'Placa da obra', weight: 3 },
  { id: '29-04', category: 'SINALIZACAO', question: 'Indicadores de segurança no sistema de gestão à vista', weight: 3 },

  // 30. DOCUMENTAÇÃO BÁSICA
  { id: '30-01', category: 'DOCUMENTACAO_BASICA', question: 'Outros', weight: 2 },
  { id: '30-02', category: 'DOCUMENTACAO_BASICA', question: 'Documentação (contrato, estagiários)', weight: 4 },
  { id: '30-03', category: 'DOCUMENTACAO_BASICA', question: 'Ficha de registro', weight: 3 },
  { id: '30-04', category: 'DOCUMENTACAO_BASICA', question: 'CTPS', weight: 4 },
  { id: '30-05', category: 'DOCUMENTACAO_BASICA', question: 'ASO conforme PCMSO', weight: 4 },
  { id: '30-06', category: 'DOCUMENTACAO_BASICA', question: 'PGRO e inventário de riscos', weight: 4 },
  { id: '30-07', category: 'DOCUMENTACAO_BASICA', question: 'PCMSO', weight: 4 },
  { id: '30-08', category: 'DOCUMENTACAO_BASICA', question: 'APR das atividades', weight: 4 },
  { id: '30-09', category: 'DOCUMENTACAO_BASICA', question: 'Permissão de trabalho para atividades críticas', weight: 4 },

  // 31. TREINAMENTOS
  { id: '31-01', category: 'TREINAMENTOS', question: 'Outros', weight: 2 },
  { id: '31-02', category: 'TREINAMENTOS', question: 'Ordem de serviço NR-01', weight: 4 },
  { id: '31-03', category: 'TREINAMENTOS', question: 'NR-18 inicial, básico ou periódico (4 h)', weight: 5 },
  { id: '31-04', category: 'TREINAMENTOS', question: 'Integração à obra', weight: 4 },
  { id: '31-05', category: 'TREINAMENTOS', question: 'NR-06 – EPIs', weight: 4 },
  { id: '31-06', category: 'TREINAMENTOS', question: 'Diálogos de segurança', weight: 3 },
  { id: '31-07', category: 'TREINAMENTOS', question: 'NR-12 – máquinas e equipamentos', weight: 4 },
  { id: '31-08', category: 'TREINAMENTOS', question: 'NR-35 – trabalho em altura', weight: 5 },
  { id: '31-09', category: 'TREINAMENTOS', question: 'NR-33 – espaço confinado (vigias, autorizados, supervisor)', weight: 4 },
  { id: '31-10', category: 'TREINAMENTOS', question: 'Treinamento para misturadores e betoneiras', weight: 4 },
  { id: '31-11', category: 'TREINAMENTOS', question: 'Operador de PEMT', weight: 4 },
  { id: '31-12', category: 'TREINAMENTOS', question: 'Instalação, montagem, desmontagem de elevador cremalheira', weight: 4 },
  { id: '31-13', category: 'TREINAMENTOS', question: 'Operador de cremalheira', weight: 4 },
  { id: '31-14', category: 'TREINAMENTOS', question: 'Operador de grua', weight: 4 },
  { id: '31-15', category: 'TREINAMENTOS', question: 'Operador de guindaste', weight: 4 },
  { id: '31-16', category: 'TREINAMENTOS', question: 'Treinamento mensal para sinaleiros e envolvidos em movimentação de carga', weight: 3 },
  { id: '31-17', category: 'TREINAMENTOS', question: 'Treinamento para revolver finca pino', weight: 5 },
  { id: '31-18', category: 'TREINAMENTOS', question: 'Eletricistas (NR-10) + capacitação eletricista', weight: 4 },
  { id: '31-19', category: 'TREINAMENTOS', question: 'Montagem, operação de balancim e cadeirinha', weight: 4 },
  { id: '31-20', category: 'TREINAMENTOS', question: 'Treinamento representante CIPA', weight: 4 },

  // 32. DOCUMENTAÇÃO LEGAL
  { id: '32-01', category: 'DOCUMENTACAO_LEGAL', question: 'Outros', weight: 2 },
  { id: '32-02', category: 'DOCUMENTACAO_LEGAL', question: 'Alvarás (demolição, construção, avanço de tapume e grua), ART da obra', weight: 5 },
  { id: '32-03', category: 'DOCUMENTACAO_LEGAL', question: 'Comunicação prévia e livro de inspeção do MTE', weight: 4 },

  // 33. PROGRAMAS E PROJETOS
  { id: '33-01', category: 'PROGRAMAS', question: 'Outros', weight: 2 },
  { id: '33-02', category: 'PROGRAMAS', question: 'PGR NR 18 e anexos', weight: 5 },
  { id: '33-03', category: 'PROGRAMAS', question: 'Projetos e ARTs das proteções coletivas', weight: 4 },
  { id: '33-04', category: 'PROGRAMAS', question: 'Projetos e ARTs das linhas de vida', weight: 4 },
  { id: '33-05', category: 'PROGRAMAS', question: 'Projetos e ARTs de passarela, escadas e rampas', weight: 4 },
  { id: '33-06', category: 'PROGRAMAS', question: 'Projetos e ARTs dos andaimes', weight: 4 },

  // 34. ACIDENTES E INCIDENTES
  { id: '34-01', category: 'ACIDENTES', question: 'Outros', weight: 2 },
  { id: '34-02', category: 'ACIDENTES', question: 'Houve acidentes no mês referido', weight: 5 },
  { id: '34-03', category: 'ACIDENTES', question: 'Houve incidente no mês referido', weight: 4 },
];